export const UserLoginActions = {
	USER_LOADING: "USER_LOADING",
	USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
	USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
	USER_LOGOUT: "USER_LOGOUT",
};

export const RegisterActions = {
	REGISTER_WORKER: "REGISTER_WORKER",
	REGISTER_NUMBER: "REGISTER_NUMBER",
	REGISTER_USER: "REGISTER_USER",
	REGISTER_LOCATION: "REGISTER_LOCATION",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_LOADING: "REGISTER_LOADING",
	REGISTER_FAIL: "REGISTER_FAIL",
	REGISTER_LOGOUT: "REGISTER_LOGOUT",
};

export const UserDetailActions = {
	USER_DETAILS_LOADING: "USER_DETAILS_LOADING",
	USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
	USER_DETAILS_CHANGE_ADDRESS: "USER_DETAILS_CHANGE_ADDRESS",
	USER_DETAILS_CHANGE_ACCOUNT_INFO: "USER_DETAILS_CHANGE_ACCOUNT_INFO",
	USER_DETAILS_CHANGE_SUCCESS: "USER_DETAILS_CHANGE_SUCCESS",
	USER_DETAILS_CHANGE_PENDING_VERIFICATION:
		"USER_DETAILS_CHANGE_PENDING_VERIFICATION",
	USER_DETAILS_FAIL: "USER_DETAILS_FAIL",
	USER_DETAILS_LOGOUT: "USER_DETAILS_LOGOUT",
};
